"use client";
import {useEffect,useMemo,useState} from "react";
type Status="Atrasada"|"Próxima"|"Planejada"|"Realizada";
type Visit={id:number,date:string,client:string,farm:string,sector:string,visit:string,area:number,status:Status,delay:number,account:string};
const demoVisits:Visit[]=[
{id:1,date:"16 ago",client:"WJ Agropecuária",farm:"Faz. Baixa Alegre",sector:"A",visit:"VT3",area:48.2,status:"Atrasada",delay:12,account:"DRF1"},
{id:2,date:"18 ago",client:"Agropecuária Londrina",farm:"Faz. Londrina I",sector:"C",visit:"VT2",area:49.9,status:"Próxima",delay:0,account:"DRF2"},
{id:3,date:"19 ago",client:"Carlos Henrique Marx",farm:"Faz. Pedra Polida",sector:"C",visit:"VT1",area:28.5,status:"Próxima",delay:0,account:"DRF2"},
{id:4,date:"21 ago",client:"Breno Martins",farm:"Faz. Realidade",sector:"A",visit:"VT4",area:14.8,status:"Planejada",delay:0,account:"DRF1"},
{id:5,date:"14 ago",client:"Airson Eugênio",farm:"Arr. Nova América",sector:"A",visit:"VT2",area:44.1,status:"Realizada",delay:0,account:"DRF1"}];
const nav=["Visão geral","Agenda","Clientes","Áreas e ciclos","Relatórios"];
export default function Home(){const[active,setActive]=useState("Visão geral");const[filter,setFilter]=useState("Todas");const[query,setQuery]=useState("");const[modal,setModal]=useState(false);const[visits,setVisits]=useState<Visit[]>(demoVisits);const[source,setSource]=useState("demo");const[counts,setCounts]=useState({visits:1233,completed:261,delayed:758});useEffect(()=>{fetch("/api/operacao").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(data.visits?.length){setVisits(data.visits);setCounts(data.counts);setSource("google-sheets")}}).catch(()=>{})},[]);const filtered=useMemo(()=>visits.filter(v=>(filter==="Todas"||v.status===filter)&&`${v.client} ${v.farm}`.toLowerCase().includes(query.toLowerCase())),[filter,query,visits]);return <main className="shell">
<aside className="sidebar"><div className="brand"><span>M</span><div><strong>Monitora</strong><small>desenvolvida pela Vejho</small></div></div><nav>{nav.map((item,i)=><button key={item} className={active===item?"active":""} onClick={()=>setActive(item)}><i>{["⌂","▣","♙","◇","▥"][i]}</i>{item}</button>)}</nav><div className="user"><b>WL</b><div><strong>Wesley Ornelas</strong><small>Gestor operacional</small></div></div></aside>
<section className="workspace"><header><div><p className="eyebrow">CENTRO DE OPERAÇÕES</p><h1>{active}</h1></div><button className="primary" onClick={()=>setModal(true)}>＋ Nova visita</button></header>
{active==="Visão geral"&&<><section className="hero"><div><p>Boa tarde, Wesley</p><h2>A operação requer atenção em <em>758 visitas atrasadas.</em></h2><span>Atualizado hoje, 16 de agosto • Dados consolidados da operação</span></div><div className="ring"><b>61,5%</b><small>em atraso</small></div></section><div className="filters"><label>Conta corrente<select><option>Todas as contas</option><option>DRF1 — Wesley Ornelas</option><option>DRF2 — Luiz Henrique</option></select></label><label>Cliente<select><option>Todos os clientes</option><option>WJ Agropecuária</option></select></label><label>Período<select><option>Agosto de 2026</option></select></label></div><section className="metrics">{[["▦","Visitas planejadas","1.233","+8,4% no período","blue"],["✓","Realizadas","261","21,2% do total","green"],["!","Atrasadas","758","497 críticas","red"],["→","Próximos 7 dias","24","em 11 clientes","amber"]].map(m=><article key={m[1]}><span className={m[4]}>{m[0]}</span><div><small>{m[1]}</small><b>{m[2]}</b><p>{m[3]}</p></div></article>)}</section><section className="grid2"><article className="panel"><Title title="Progresso dos monitoramentos" text="Distribuição por etapa do ciclo"/>{[["VT1",300,174],["VT2",330,66],["VT3",303,19],["VT4",300,2]].map(([n,t,d])=><div className="progress" key={n as string}><div><b>{n}</b><span>{d} de {t} realizadas</span><strong>{Math.round(Number(d)/Number(t)*100)}%</strong></div><div><i style={{width:`${Number(d)/Number(t)*100}%`}}/></div></div>)}</article><article className="panel"><Title title="Próximas visitas" text="Prioridades dos próximos dias"/><div className="miniList">{visits.slice(0,4).map(v=><div key={v.id}><span className="date"><b>{v.date.split(" ")[0]}</b><small>AGO</small></span><div><b>{v.client}</b><small>{v.farm} • {v.visit}</small></div><em className={v.status.toLowerCase()}>{v.status}</em></div>)}</div></article></section></>}
{active==="Agenda"&&<section className="panel full"><div className="agendaHead"><div><h2>Agenda de monitoramentos</h2><p>Organize, filtre e conclua as visitas da equipe.</p></div><div className="segmented">{["Todas","Atrasada","Próxima","Planejada","Realizada"].map(s=><button className={filter===s?"selected":""} onClick={()=>setFilter(s)} key={s}>{s}</button>)}</div></div><div className="tableTools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente ou fundo agrícola"/><span>{filtered.length} visitas encontradas</span></div><div className="tableWrap"><table><thead><tr><th>Data</th><th>Cliente / fundo</th><th>Setor</th><th>Visita</th><th>Área</th><th>Conta</th><th>Status</th></tr></thead><tbody>{filtered.map(v=><tr key={v.id}><td><b>{v.date}</b></td><td><b>{v.client}</b><small>{v.farm}</small></td><td>{v.sector}</td><td><b>{v.visit}</b></td><td>{v.area.toFixed(1)} ha</td><td>{v.account}</td><td><em className={v.status.toLowerCase()}>{v.status}{v.delay?` • ${v.delay}d`:""}</em></td></tr>)}</tbody></table></div></section>}
{active==="Clientes"&&<Empty title="Clientes e contas" text="Cadastros únicos evitam duplicidades e diferenças de grafia." action="Cadastrar cliente"/>}{active==="Áreas e ciclos"&&<Empty title="Áreas e ciclos agrícolas" text="Cadastre fundos, setores e datas para gerar VT1–VT4 automaticamente." action="Cadastrar ciclo"/>}{active==="Relatórios"&&<Empty title="Relatórios operacionais" text="Acompanhe execução, atrasos, metas semanais e desempenho por conta." action="Gerar relatório"/>}</section>
{modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}>×</button><p className="eyebrow">NOVO MONITORAMENTO</p><h2>Agendar visita</h2><p>Registre uma visita extraordinária ou ajuste o planejamento.</p><div className="formGrid"><label>Cliente<select><option>Selecione um cliente</option><option>WJ Agropecuária</option></select></label><label>Fundo agrícola<select><option>Selecione o fundo</option></select></label><label>Tipo de visita<select><option>VT1</option><option>VT2</option><option>VT3</option><option>VT4</option></select></label><label>Data prevista<input type="date"/></label><label className="wide">Responsável<select><option>Wesley Ornelas</option><option>Luiz Henrique</option></select></label></div><div className="modalActions"><button onClick={()=>setModal(false)}>Cancelar</button><button className="primary" onClick={()=>setModal(false)}>Salvar visita</button></div></section></div>}</main>}
function Title({title,text}:{title:string,text:string}){return <div className="panelTitle"><div><h3>{title}</h3><p>{text}</p></div><button>Ver detalhes</button></div>}
function Empty({title,text,action}:{title:string,text:string,action:string}){return <section className="empty panel"><span>◇</span><h2>{title}</h2><p>{text}</p><button className="primary">＋ {action}</button></section>}
